name: Raid
version: '1.0-SNAPSHOT'
main: com.lunar.raid.Raid.Raid
api-version: '1.21'
authors: [Lunar]
description: Raid plugin that spawns MythicMobs to defend claims
depend: [SCore, ExecutableItems, Towny, MythicMobs]

commands:
  raid:
    description: Start a raid by spawning a MythicMob in a claimed area
    usage: /<command>
    permission: raid.use
    permission-message: You don't have permission to use this command!

  townupgrade:
    description: Opens the upgrade GUI
    usage: /<command>

  upgrades:
    description: View and apply town upgrades
    usage: /<command>
    permission: town.upgrade
    permission-message: You can't do that!

  earth:
    description: Opens the Earth main GUI
    usage: /<command>
    permission: earth.menu
    permission-message: You can't use this.

  stamp:
    description: Stamp an item with a specific upgrade ID in its lore
    usage: /stamp <upgrade-id>

permissions:
  raid.use:
    description: Allows the use of the raid command
    default: true

  town.upgrade:
    description: Allows the user to upgrade their town’s defense
    default: op

  earth.menu:
    description: Allows the user to access the Earth menu
    default: op
